## Use this file to configure SwiftLint. See github.com/realm/SwiftLint for more info.
disabled_rules: # rule identifiers to exclude from running
- file_length
- function_body_length
- line_length
- missing_docs
- private_outlet
- cyclomatic_complexity
- trailing_whitespace
- identifier_name
opt_in_rules: # some rules are only opt-in
# Find all the available rules by running: swiftlint rules
- force_unwrapping
- empty_count
- trailing_semicolon
- closure_parameter_position
- closure_spacing
- explicit_init
- function_body_length
- implicit_return
- implicitly_unwrapped_optional
- let_var_whitespace
- line_length
- literal_expression_end_indentation
- operator_usage_whitespace
- overridden_super_call
- private_action
- private_outlet
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- required_enum_case
- single_test_class
- sorted_first_last
- statement_position
- switch_case_on_newline
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- yoda_condition
included: # paths to include during linting. `--path` is ignored if present.
- Health
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
# Customize behaviour of the existing rules
large_tuple: 5
nesting:
type_level: 2
statement_level: 5
type_body_length:
- 400 # warning
- 500 # error

